# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transparent.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_transparentWidget(object):
    def __init__(self):
        self.label = None
        self.horizontalLayout = None

    def setupUi(self, transparentWidget:QtWidgets.QWidget):
        transparentWidget.setObjectName("transparentWidget")
        transparentWidget.resize(226, 57)
        self.horizontalLayout = QtWidgets.QHBoxLayout(transparentWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(transparentWidget)
        self.label.setText("one")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)

        self.retranslateUi(transparentWidget)
        QtCore.QMetaObject.connectSlotsByName(transparentWidget)

        transparentWidget.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        transparentWidget.setAttribute(QtCore.Qt.WA_TranslucentBackground)

    def retranslateUi(self, transparentWidget):
        _translate = QtCore.QCoreApplication.translate
        transparentWidget.setWindowTitle(_translate("transparentWidget", "Form"))
